### PR TITLE
Community modal

### PR DESCRIPTION
**Pull request by railsstudent**
screen shot 2017-06-07 at 10 13 44 pm

### CODE REVIEW

**Comment by railsstudent** [comment]
screen shot 2017-06-08 at 7 32 58 am
screen shot 2017-06-08 at 7 33 10 am



screen shot 2017-06-08 at 7 33 42 am

**Comment by railsstudent** [comment]
screen shot 2017-06-08 at 7 33 19 am
screen shot 2017-06-08 at 7 33 28 am
screen shot 2017-06-08 at 7 33 38 am

**Comment by railsstudent** [comment]
screen shot 2017-06-08 at 8 43 55 pm
screen shot 2017-06-08 at 8 44 01 pm

**Review by yookoala — APPROVED** [review]
Really nice work.

**Pull request merged**
