### PR TITLE
Improve in background photo

### PR DESCRIPTION
**Pull request by tonyhhyip**

### CODE REVIEW

**Comment by tonyhhyip** [comment]
Remark: request from marketing team

**Review by yookoala — COMMENTED** [review]
Why is there no change in `yarn.lock`? Should it?

**Review by yookoala — COMMENTED** [review]
The new image is smaller in size. Is it on purpose or is it a mistake?

**Comment by tonyhhyip** [comment]
@yookoala Just github is lazy to show, there is change in `yarn.lock`

**Comment by yookoala** [comment]
@tonyhhyip: understood.

**Comment by yookoala** [comment]
And the image size? Is that a requested change?

**Comment by tonyhhyip** [comment]
Nicholas claim that it should be ok to have 720 size

**Review by yookoala — APPROVED** [review]

**Pull request merged**
