### PR TITLE
Refactor redux store

### PR DESCRIPTION
**Pull request by tonyhhyip**

### CODE REVIEW

**Comment by yookoala** [comment]
1. It makes sense to have a separated reducer for user. But it doesn't make sense to have separated reducer for sessions, topics and venues. The data of sessions, topics, and venues are used together. We need to have them in the same reducer / store.

2. After reviewing the approach last year, I now think it makes more sense to put the actions into the same file as the store that uses them. (i.e. user store file holds the actions about user).

**Review by yookoala — CHANGES_REQUESTED** [review]
Separating the reducer to too many portion. Some of them might not even has its own action. Please combine some of them.

**Comment by tonyhhyip** [comment]
@yookoala No idea on how to combine some of them while keeping the user reducer outside

**Comment by yookoala** [comment]
Suggest to have a `data` reducer to do the `sessions`, `topics` and `venues`. Also a `user` reducer to deal with `user`. Then use `combineReducer` on these 2 reducers (not 5).

The resulting store should look like this:

```
{
  "data": {
    "sessions": {},
    "topics": {},
    "veunes": {},
  },
  "user": {}
}
```

When the user is doing filtering, `data` reducer should tag the sessions / topics with flags (e.g. `data.sessions.some_session.highlighted = true` or `data.topics.some_topic.highlighted = true` or both).

**Review by yookoala — APPROVED** [review]

**Pull request merged**
