### PR TITLE
Add Call For Proposals Results page.

### PR DESCRIPTION
**Pull request by railsstudent**
#50 

When program team announces CFP results in April/May, this page can be released after cfp.yml is updated.

### CODE REVIEW

**Comment by tonyhhyip** [comment]
@railsstudent Need to make confirm

**Comment by yookoala** [comment]
Can we do the data in `topics.yml`? The topics should basically be the same. No need to duplicate the data entry. If not all entries are CFP, just add a flag `cfp` into topics. Then the CFP result page can show only topics with `cfp === true`.

**Comment by tonyhhyip** [comment]
@yookoala This cannot be released for current

**Comment by yookoala** [comment]
@tonyhhyip I understand.

**Review by yookoala — COMMENTED** [review]
Would be best to rename `results` in topics.yml to `topics` (so `data.topics.topics` in template). Seems more appropriate for other usage (e.g. rendering topic pages and timetable).

**Comment by yookoala** [comment]
No rush. Still pending other teams to approve the content.

**Comment by tonyhhyip** [comment]
We can start putting on CFP result

**Review by yookoala — APPROVED** [review]

**Comment by railsstudent** [comment]
I can change the property name in yml file at the loop tonight.

**Pull request merged**
