### PR TITLE
Timetable topic modal

### PR DESCRIPTION
**Pull request by railsstudent**
If not using iframe to show topic page,Please suggest alternative.  I would like reuse html pages already exist

### CODE REVIEW

**Comment by tonyhhyip** [comment]
Please check what happened
screenshot from 2017-05-22 09-49-31

**Comment by railsstudent** [comment]
Fixed.

**Comment by railsstudent** [comment]
selection_014
selection_015

**Comment by tonyhhyip** [comment]
iframe is not a good idea

**Comment by tonyhhyip** [comment]
@railsstudent I just build the page and test it, I find you have made iframe and modal for every page, this is not effective and efficient. I am resolving on this

**Pull request merged**
