### PR TITLE
Bug fixes to topic.yml and speaker.yml

### PR DESCRIPTION
**Pull request by railsstudent**
Fix lang-slide to lang_slide
Update portrait of various speakers
Fix nationality of 趙惟倫 to Taiwan

### CODE REVIEW

**Review by yookoala — COMMENTED** [review]
Please help to check if we have the permission to all the images here. Thanks.

**Review by yookoala — CHANGES_REQUESTED** [review]
Please remove image for Eric Sun and Ivan Ma. Thanks.

**Comment by railsstudent** [comment]
Removed.

**Review by yookoala — APPROVED** [review]

**Comment by yookoala** [comment]
Thanks Connie!

**Pull request merged**
